# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PhoenixClientPractice' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
    pod "SwiftPhoenixClient/RxSwift", '~> 2.0'
    pod "SwiftPhoenixClient", '~> 2.0'
    pod 'RxSwift'
    pod 'RxCocoa'

  # Pods for PhoenixClientPractice

  target 'PhoenixClientPracticeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PhoenixClientPracticeUITests' do
    # Pods for testing
  end

end
